### PR TITLE
redid seeding to be more robust

### PR DESCRIPTION
**Pull request by danielmmetz**
Check it.

### CODE REVIEW

**Comment by ericthewry** [comment]
Figured out how to  make search fast:

When we access collections we get call

``` ruby
collections = Collection.includes(:rooms)
```

~~~This generates a 10.5ms database call that load the associated table into memory~~~
**_EDIT**_. It generates 2. One for the Collections, which is about 11+/- 2 ms, and another that loads all of Rooms into memory that is ~ 3ms.

Then in the loop,

``` ruby
collections.find_each do |c| # maybe this can be `each`, not sure
    rooms = c.rooms # get the rooms associated with the collection for free
     ...
end
```

Will also have to set line `app/models/collection.rb:3` to 

``` ruby
has_many :rooms
```

**Comment by ericthewry** [comment]
More info:

So, if we have some `c = collections.includes(:rooms)[100]` then the command 

``` ruby
c.rooms.sum :capacity
```

We trigger a database call 

``` SQL
(3.0ms)  SELECT SUM("rooms"."capacity") FROM "rooms" WHERE "rooms"."collection_id" = $1  [["collection_id", 101]]
=> 4
```

That's not a great efficiency boost. We'll still be performing the aggregation calls; however,

``` ruby
c[100].rooms[1].capacity
```

is once again 'free'.

**Comment by kwynn** [comment]
This looking promising but I think we should talk about this more when we're together as load times are pretty vital to the user experience.

**Comment by ericthewry** [comment]
Waiting on #27.  Should be good to merge once thats done.

**Pull request merged**
